#pragma once
#include <stdint.h>

namespace Core
{
	namespace Random
	{
		// Global seed (we use a 'global' mt19937 generator)
		void ResetGlobalSeed();		// resets the seed to a random number generated by std::random_device
		void SetGlobalSeed(uint32_t seed);	// set a specific global seed

		// Value generators
		float GetFloat(float minval = 0.0f, float maxval = 1.0f);
		int GetInt(int minval = 0, int maxval = INT32_MAX);
	}
}